" loading pathogen at runtime as it's bundled
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()

" Wrap
set nowrap
" If you like long lines with line wrapping enabled, this solves the problem that pressing down jumpes your cursor “over” the current line to the next line. It changes behaviour so that it jumps to the next row in the editor (much more natural):

nnoremap j gj
nnoremap k gk

set nocompatible  " Use Vim settings, rather then Vi settings
set nobackup
set nowritebackup
set notimeout
set ttimeout
set ttimeoutlen=10
set noswapfile                    " It's 2012, Vim."
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands

" misc
set history=500
set undolevels=1000
set wildignore=*.swp,*.bak,*.class,*.pyc

" search 
set incsearch     " do incremental searching
set hlsearch
set smartcase     " ignore case if search pattern is all lowercase,
                  "    case-sensitive otherwise
                  "

"Tired of clearing highlighted searches by searching for “ldsfhjkhgakjks”? Use this:
nmap <silent> ,/ :nohlsearch<CR>

" sudo save
cmap w!! w !sudo tee % >/dev/null

set laststatus=2  " Always display the status line
set t_Co=256
syntax on

" Send more characters for redraws
set ttyfast

" Use Bash as shell
set shell=/usr/local/bin/bash

" Enable mouse use in all modes
set mouse=a
set ttymouse=xterm2

filetype plugin indent on

" Softtabs, 4 spaces
set tabstop=2
set shiftwidth=2
set expandtab
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'

" Display extra whitespace
" set list listchars=tab:»·,trail:·
"
" Clipboard fix for OsX
set clipboard=unnamed

" Numbers
set number
set numberwidth=2

"Folding
set foldmethod=indent
set foldlevelstart=99

" Autocompletion options
set wildmode=list:longest,list:full
set complete=.,w,b

" Tags
let Tlist_Ctags_Cmd = "/usr/local/bin/ctags -R --exclude=.git --exclude=log -f ./.tags *"
set tags+=.tags

source $HOME/.vim/autocommands.vim
source $HOME/.vim/plugins.vim
source $HOME/.vim/shortcuts.vim
source $HOME/.vim/rails.vim
source $HOME/.vim/syntax.vim
source $HOME/.vim/tmux.vim
source $HOME/.vim/visual_fixes.vim
source $HOME/.vim/scala.vim

" source $HOME/.vim/neocomplcache.vim
" let g:neocomplcache_enable_at_startup = 1
